version: '3.6'

services:

  server:
    image: nginx:alpine
    working_dir: /server
    volumes:
      - ./dist:/server
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: ['1234:1234']
    links: [bundler]

  bundler:
    image: node:alpine
    working_dir: /bundler
    command: npm run bundler
    volumes: ['.:/bundler']
    ports: ['42635:42635']
